name: 📃 Documentação de componente
description: Template para documentação de componentes
title: "[Documentação de Componente]: "
labels: ["frente: acessibilidade", "documentação de componente"]
projects: ["VivoDesignTeam/26"]
body:
  - type: input
    id: component
    attributes:
      label: Componente
      placeholder: Nome do componente
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descrição
      placeholder: Conte-nos um pouco mais sobre esse componente
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Produto
      options:
        - MVE
        - Novo App
        - App As is (Atual)
        - Loja de CE
        - Loja de Serviços
        - On Going
        - Portal
    validations:
      required: true
  - type: input
    id: squad
    attributes:
      label: Squad/Frente
      placeholder: Nome da squad
    validations:
      required: true
  - type: input
    id: figma-link
    attributes:
      label: Link Figma
      description: Informe o link da documentação a ser revisada
      placeholder: Link do Figma
    validations:
      required: true
  - type: dropdown
    id: novo-comp
    attributes:
      label: Este é um componente novo ou alteração?
      options:
        - Novo componente
        - Alteração em componente existente
    validations:
      required: true
  - type: input
    id: relator
    attributes:
      label: Relator do pedido
      placeholder: Seu nome
    validations:
      required: true
  - type: input
    id: ambassador
    attributes:
      label: Embaixador de acessibilidade
      placeholder: Nome do embaixador (Se tiver)
    validations:
      required: false